virginia:   us-east-1
california: us-west-1
oregon:     us-west-2
ireland:    eu-west-1
frankfurt:  eu-central-1
tokyo:      ap-northeast-1
seoul:      ap-northeast-2
singapore:  ap-southeast-1
sydney:     ap-southeast-2
sao_paulo:  sa-east-1
